### ISSUE TITLE
unable to run your 3d_face_class on the RPi 4B platform.

### ISSUE THREAD

**Issue by suijunqiang** [w00zie/3d_face_class#1]
First of all, thanks to share your great project.
but it's unable to run on my RaspiBerry 4B with the errors as below with the command:
$ python test.py --exp_dir ./runs/bosphorus

Testing ./runs/bosphorus/

> Traceback (most recent call last):
>   File "/home/pi/src/ai/3d_face_class/test.py", line 39, in <module>
>     train_list, test_list = get_train_test_split(config=config,
>   File "/home/pi/src/ai/3d_face_class/data.py", line 198, in get_train_test_split
>     train_list = _build_data_list(config, data_dir, train_ids, classes_dict)
>   File "/home/pi/src/ai/3d_face_class/data.py", line 211, in _build_data_list
>     e = np.load(e_fname)
>   File "/home/pi/.local/lib/python3.9/site-packages/numpy/lib/npyio.py", line 407, in load
>     fid = stack.enter_context(open(os_fspath(file), "rb"))
> FileNotFoundError: [Errno 2] No such file or directory: 'graph_data/bosphorus_full/bs009/edges_bs009_LFAU_17_0.npy'

By the way, the test commands unable to find in your projects, such as there is not /runs//exp000 but runs/bosphorus & runs/frgc

Thanks & Best Regards
Sui

**Comment by w00zie** [comment]
Hi @suijunqiang , sorry for the late reply, i don't know how but i missed the notification on this!
Regarding your problem: the `FileNotFoundError` error is due to the absence of any data under `graph_data/`. 
I cannot share the data i used so you'll need to train a model on your data, unfortunately.
I can help you with that but it's mandatory for you to provide the data (either as meshes or graphs).
Hope i answered your question.
Thanks for the interest in this project and sorry again for the late reply

**Comment by suijunqiang** [comment]
Anyway thanks for your help& supports.
I will ask you again, if any other issue.

Thanks & Regards
Sui

**Comment by w00zie** [comment]
As I pointed out #2, you  can ask permission to use the Bosphorus dataset [here](http://bosphorus.ee.boun.edu.tr/Home.aspx) or scrape through 3D face datasets (e.g. [here](https://paperswithcode.com/datasets?mod=3d)).
